import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans ,DM_Sans,Fraunces} from "next/font/google";
import "./globals.css";
import ContextProvider from "@/context";
import { headers } from "next/headers";
import { LayoutShell } from "@/components/common/layout-shell";

const notoSans = Noto_Sans({
	variable: "--font-sans",
	subsets: ["latin"],
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const dmSans = DM_Sans({
	variable: "--font-dm-sans",
	subsets: ["latin"],
	weight: ["400", "500", "700"],
});

const fraunces = Fraunces({
	variable: "--font-fraunces",
	subsets: ["latin"],
	weight: ["400", "500", "700"],
});



export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const headersObj = await headers();
	const cookies = headersObj.get("cookie");
	return (
		<html lang="en" className={notoSans.variable}>
			<body
				className={` ${dmSans.variable} ${fraunces.variable} antialiased`}
			>
				<ContextProvider cookies={cookies}>
					<LayoutShell>{children}</LayoutShell>
				</ContextProvider>
			</body>
		</html>
	);
}
